POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"tue291000",
    "password":"1"
}

# GET http://localhost:5000/api/post
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYyMTJmYmRlMjU0NmQxMGZkMzE1NTQiLCJpYXQiOjE2NTA2MDUwNzV9.RVIm6VpMwSRa6pwtc0ufStfxjoHUQztbsAYGr-hmp-A

# {
#     "title":"Reactjs",
#     "description":"Reactjs",
#     "url":"react.com",
#     "status":"TO LEARN"
# }

# GET https://localhost:5000/api/post
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYyMTJmYmRlMjU0NmQxMGZkMzE1NTQiLCJpYXQiOjE2NTA2MDUwNzV9.RVIm6VpMwSRa6pwtc0ufStfxjoHUQztbsAYGr-hmp-A


